# Docker composor for the default virtual 6IDD testing ENV
version: '3.7'

services:
  caRepeat:
    container_name: caRepeater
    image: kedokudo/virtualbeamline:epics-base
    networks:
      - vbnet6idd
    entrypoint:
      - bin/linux-x86_64/caRepeater
  
  ioc6iddsimmtr:
    container_name: ioc6iddsimmtr
    image: kedokudo/virtualbeamline:ioc6iddsimmtr
    stdin_open: true
    tty: true
    networks:
      - vbnet6idd
    environment:
      - IOC_PREFIX='6iddSIM:'
      - IOCNAME='6iddSIM'
    expose:
      - "5064" 
      - "5065"
    depends_on:
      - caRepeat
  
  ioc6iddsimdet:
    container_name: ioc6iddsimdet
    image: kedokudo/virtualbeamline:ioc6iddsimdet
    stdin_open: true
    tty: true
    networks:
      - vbnet6idd
    environment:
      - IOC_PREFIX='6iddSIMDET1:'
    expose:
      - "5064" 
      - "5065"
    depends_on:
      - caRepeat
  
  console:
    container_name: console
    image: kedokudo/virtualbeamline:epics-base
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/bash
    networks:
      - vbnet6idd
    depends_on:
      - caRepeat
      - ioc6iddsimdet
      - ioc6iddsimmtr

  caQTDM:
    container_name: caQTDM
    image: kedokudo/virtualbeamline:caQTDM
    stdin_open: true
    tty: true
    entrypoint:
      - /bin/bash
    networks:
      - vbnet6idd
    depends_on:
      - caRepeat
      - ioc6iddsimdet
      - ioc6iddsimmtr
  
  mongo:
    container_name: mongoDB
    image: mongo
    ports:
      - "27017:27017"

  frontend:
    container_name: jupyterlab
    image: kedokudo/virtualbeamline:jupyter
    stdin_open: true
    tty: true
    entrypoint:
      - "jupyter"
      - "lab"
      - "--ip=0.0.0.0"
      - "--no-browser"
      - "--allow-root"

networks:
  vbnet6idd:
    driver: bridge